name: Bug report
description: Report a defect in a plugin or repository workflow
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough detail to reproduce it.

  - type: input
    id: plugin
    attributes:
      label: Plugin
      description: Which plugin is affected?
      placeholder: strategy-toolkit
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Plugin version
      placeholder: 0.1.0
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Share exact steps, commands, and inputs.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or output
      description: Paste relevant logs, stack traces, or command output.
      render: shell
    validations:
      required: false
