name: Feature request
description: Propose a new plugin feature or repository improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an improvement.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: Current workflow is missing...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your preferred solution.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches evaluated?
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Expected impact
      description: Who benefits and how?
    validations:
      required: true
